### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by mzprose** [mousecpn/Joint-Bilateral-Learning#3]
Hello,there is a problem when I run test.py:
Traceback (most recent call last):
  File "test.py", line 67, in <module>
    test(params)
  File "test.py", line 42, in test
    cont_feat = net.encode_with_intermediate(low_cont)
"RuntimeError: Expected 4-dimensional input for 4-dimensional weight 3 3 1 1, but got 3-dimensional input of size [3, 256, 256] instead"

input :single image

could you help me?

**Comment by mousecpn** [comment]
modify the code like that:
cont_feat = net.encode_with_intermediate(low_cont.unsqueeze(0))
style_feat = net.encode_with_intermediate(low_style.unsqueeze(0))
coeffs, output = model(cont_img.unsqueeze(0), cont_feat, style_feat)

**Comment by mzprose** [comment]
thank you,problem solved successfully.
